### ISSUE TITLE
Przechylony obraz

### ISSUE THREAD

**Issue by mysliwy112** [Dove6/dePIKczer#1]
Przy konwersji obrazów z przezroczystością / szerokością lub wysokością niepodzielną przez 8 skonwertowany obraz wychodzi pochyły

**Comment by Dove6** [comment]
Prace w toku. Problem nie wynika z obecności kanału alpha nieobjętego nagłówkiem BMP, jak początkowo sądziliśmy, a koniecznością wyrównania każdej linii zapisanych danych bitmapy do czterech bajtów.
W związku z tym usuwam powiązanie z [kamieniem milowym dot. przezroczystości](https://github.com/Dove6/dePIKczer/milestone/1).

**Comment by Dove6** [comment]
Problem rozwiązany wraz z [najświeższym commitem](https://github.com/Dove6/dePIKczer/commit/98a042ffdf6851ecf4050fd315d1a3f96235085d).
