### ISSUE TITLE
Collision

### ISSUE THREAD

**Issue by mysliwy112** [Dove6/dePIKczer#2]
Some images responsible for collision are unreadable after conversion.

Example:
\Reksio i Kretes w Akcji\dane\game\przygoda\piraci\wall0.img

**Comment by Dove6** [comment]
Fixed with [most recent commit](https://github.com/Dove6/dePIKczer/commit/8b7abf70e7f5bcb6b79611888b6da22136a6ce39). Output doesn't exactly represent input yet, but at least the output file can be opened :P

**Comment by Dove6** [comment]
[By now](https://github.com/Dove6/dePIKczer/commit/cb606c46fac43043d34b2766de45f7545f4ddf71) the problem is completely solved, with newly included RGB pixel format conversion.
